### ISSUE TITLE
Continous Console Spam with or without players online

### ISSUE THREAD

**Issue by anonynorbi** [Crazy-Crew/ChatManager#21]
Hi. I'm running a minecraft server (1.19 Paper) and I got this messages in a constant loop in the console:

```
[Server thread/WARN]: [ChatManager] Task #115 for ChatManager v3.7.7 generated an exception
java.lang.IllegalStateException: ReflectionHelper is not set up!
        at me.h1dd3nxn1nja.chatmanager.utils.JSONMessage$ReflectionHelper.createTitleTimesPacket(JSONMessage.java:755) ~[ChatManager_3.7.7.jar:?]
        at me.h1dd3nxn1nja.chatmanager.utils.JSONMessage.title(JSONMessage.java:209) ~[ChatManager_3.7.7.jar:?]
        at me.h1dd3nxn1nja.chatmanager.managers.AutoBroadcastManager$4.run(AutoBroadcastManager.java:153) ~[ChatManager_3.7.7.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-379]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-379]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-379]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

There is one more problem: if I configure configuration files and reload the plugin, the server becomes unresponsive. Rebooting the server fixes this problem.

Can you let me know how to fix these issues? (edited)

**Comment by RyderBelserion** [comment]
Update to 3.9.0 https://modrinth.com/plugin/chatmanager
