### ISSUE TITLE
[Bug Report]: Can't do /chatmanager reload

### ISSUE THREAD

**Issue by iambeingtracked** [Crazy-Crew/ChatManager#61]
### Spark link

not needed

### Server Version

1.20.4

### Server Platform

Paper

### Describe the bug

When issuing /chatmanager reload through the ingame chat, it says: "An internal error has occurred while attempting to perform this command". 
Here's what the server log says:
```
[12:15:56 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'chatmanager' in plugin ChatManager v3.11-34
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:987) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
	at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
	at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2217) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$16(ServerGamePacketListenerImpl.java:2177) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1462) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1439) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1362) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1340) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
	at java.util.regex.Matcher.getTextLength(Matcher.java:1769) ~[?:?]
	at java.util.regex.Matcher.reset(Matcher.java:415) ~[?:?]
	at java.util.regex.Matcher.<init>(Matcher.java:252) ~[?:?]
	at java.util.regex.Pattern.matcher(Pattern.java:1134) ~[?:?]
	at me.h1dd3nxn1nja.chatmanager.paper.Methods.color(Methods.java:25) ~[ChatManager-Paper-3.11-34.jar:?]
	at me.h1dd3nxn1nja.chatmanager.paper.commands.CommandChatManager.onCommand(CommandChatManager.java:42) ~[ChatManager-Paper-3.11-34.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 29 more
```

### Crate Type

None

### Steps to reproduce

1. Install chatmanger
2. use this config file: https://files.wherelinux.xyz/config.yml

### Additional context

I'm not on paper but pufferfish, but it should be the same on Paper. Also the command works if issued through the server console.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by Progressier** [comment]
Same problem on paper with default config @ryderbelserion

**Comment by ryderbelserion** [comment]
1.20.4 is not supported
