### ISSUE TITLE
Chat Manager has started spamming console (no changes made)

### ISSUE THREAD

**Issue by MomaCods** [Crazy-Crew/ChatManager#63]
### Spark link

https://spark.lucko.me/lJ2qv0zgLZ

### Plugin Version

3.7.7

### Server Version

1.20.4

### Server Platform

Paper

### Describe the bug

Upon a recent reboot chat manager is now spamming my console. I had not made any changes inside of the configs of ChatManager until it began spamming. I checked for an update. Seems I am running the latest 3.7.7 I went into the configs and tried to disable the quit messages to see if that was what was causing the spam as I could see it was something it seemed to have an issue with. This did not solve the issue.

### Crate Type

None

### Steps to reproduce

1. start the server
2. spam in console will start quite soon after

### Additional context

I was not in the configs of this plugin before it started to throw errors in the console. 

[15:37:21 WARN]: [ChatManager] Task #288 for ChatManager v3.7.7 generated an exception
java.lang.NullPointerException: Cannot invoke "net.milkbowl.vault.chat.Chat.getPlayerPrefix(org.bukkit.entity.Player)" because "me.h1dd3nxn1nja.chatmanager.hooks.VaultHook.chat" is null
        at me.h1dd3nxn1nja.chatmanager.hooks.VaultHook.getPlayerPrefix(VaultHook.java:26) ~[ChatManager_3.7.7.jar:?]
        at me.h1dd3nxn1nja.chatmanager.managers.PlaceholderManager.setPlaceholders(PlaceholderManager.java:35) ~[ChatManager_3.7.7.jar:?]
        at me.h1dd3nxn1nja.chatmanager.managers.AutoBroadcastManager$1.run(AutoBroadcastManager.java:44) ~[ChatManager_3.7.7.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-477]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-477]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1646) ~[paper-1.20.4.jar:git-Paper-477]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-477]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-477]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-477]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-477]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
You need Vault to use the plugin.

**Comment by MomaCods** [comment]
I am using Vault

**Comment by ryderbelserion** [comment]
You then need a permissions plugin.

**Comment by MomaCods** [comment]
Like I stated there were no issues prior to a reboot for a completely different issue. this is an unexpected side mission lol

**Comment by MomaCods** [comment]
ah this fixes it... it was luckperms not chatmanager but it was chat manger that alerted us thank you! I guess it is solved now
