### ISSUE TITLE
"this.chat" is null

### ISSUE THREAD

**Issue by Re-Lyz** [Crazy-Crew/ChatManager#67]
### Plugin Version

ChatManager-3.11

### Server Version

1.20.1

### Server Platform

Spigot

### Describe the bug

`[20:53:10 WARN]: [ChatManager] Task #12 for ChatManager v3.11 generated an exception
java.lang.NullPointerException: Cannot invoke "net.milkbowl.vault.chat.Chat.getPlayerPrefix(org.bukkit.entity.Player)" because "this.chat" is null
        at me.h1dd3nxn1nja.chatmanager.support.misc.VaultSupport.getPlayerPrefix(VaultSupport.java:24) ~[ChatManager-3.11.jar:?]
        at me.h1dd3nxn1nja.chatmanager.managers.PlaceholderManager.setPlaceholders(PlaceholderManager.java:47) ~[ChatManager-3.11.jar:?]
        at me.h1dd3nxn1nja.chatmanager.managers.AutoBroadcastManager$2.run(AutoBroadcastManager.java:75) ~[ChatManager-3.11.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2006]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.1.jar:git-Purpur-2006]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1507) ~[purpur-1.20.1.jar:git-Purpur-2006]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.1.jar:git-Purpur-2006]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1421) ~[purpur-1.20.1.jar:git-Purpur-2006]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[purpur-1.20.1.jar:git-Purpur-2006]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2006]`

It seems like the problem falls on the Nullptr. I'm not sure whether the problem is caused by the Vault plugin or the chatmanager ifself, but it does not affect the common utilities. But it may cause some lags in the server?

### Steps to reproduce

when player enter the server you can see the error or waring keep showing on the panel

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
Fixed because we no longer depend on Vault
